# Overrides for running in a local environment other than devpod.
logging:
  level: info
  development: false
  encoding: json
  outputPaths:
    - stdout
    - "${HOME}/.devexp/logs/ulsp/ulsp-daemon.log"
